config/routes.rb
Shifts::Application.routes.draw do

  resources :tasks do
    post :make_entry, on: :member
    get 'update_tasks', on: :collection
    get :completed_tasks, on: :member
    get :missed_tasks, on: :member
  end

  resources :shifts_tasks
  resources :calendar_feeds, only: :index
  resources :template_time_slots
  resources :stickies
  resources :announcements
  resources :links
  resources :repeating_events
  resources :restrictions
  resources :punch_clocks
  resources :punch_clock_sets
  resources :user_sessions
  resources :password_resets
  resources :user_configs, only: [:edit, :update]
  resources :sub_requests
  resources :notices do
    get 'archive', on: :collection
    get 'update_message_center', on: :collection
  end
  resources :payform_item_sets
  resources :payform_sets
  resources :department_configs, only: [:edit, :update]
  resources :requested_shifts
  resources :templates
  resources :payform_items
  resources :requested_shifts
  resources :templates



  resources :stats do
    collection do
      get  :for_user
      post :for_user
      get  :for_location
      post :for_location
      get  :index
      post :index
    end
  end


  resource :app_config, only: [:edit, :update]
  #   get :edit, on: :collection
  # end
  # get "app_config" => 'app_configs#edit', as: :edit_app_config

  resources :calendars do
    member do
      get  :prepare_copy
      get  :apply_schedule
      post :apply_schedule
      post :toggle
      post :copy
    end
    collection do
     get :prepare_wipe_range
     post :wipe_range
    end
  end


  scope '/firstrun' do
    with_options controller: 'first_run' do |f|
      f.match '/first_app_config', action: 'new_app_config', as: :first_app_config, via: :get
      f.match '/first_department', action: 'new_department', as: :first_department, via: :get
      f.match '/first_user', action: 'new_user', as: :first_user, via: :get
      f.match '/create_first_app_config', action: 'create_app_config', as: :create_first_app_config, via: :post
      f.match '/create_first_department', action: 'create_department', as: :create_first_department, via: :post
      f.match '/create_first_user', action: 'create_user', as: :create_first_user, via: :post
    end
  end

  # match 'login' => 'user_sessions#new', as: :login
  # match 'logout' => 'user_sessions#destroy', as: :logout
  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  match "email_reminders", controller: 'payforms', action: 'email_reminders', as: :email_reminders, via: [:get, :post]
  match "reminders_advanced_options", controller: 'payforms', action: 'reminders_advanced_options', as: :reminders_advanced_options, via: [:get, :post]
  match  "warnings_advanced_options", controller: 'payforms', action: 'warnings_advanced_options', as: :warnings_advanced_options, via: [:get, :post]

  #TODO: get rid of sessions controller and move logout action to user_session controller and name it cas_logout
  match "cas_logout", controller: 'sessions', action: 'logout', as: :cas_logout, via: [:get, :post]
  match 'calendar_feeds/grab/:user_id/:token', controller: 'calendar_feeds', action: 'grab', as: :calendar_feed, via: [:get, :post]
  match 'calendar_feeds/reset', controller: 'calendar_feeds', action: 'reset', as: :calendar_feed_reset, via: [:get, :post]

  # routes for managing superusers

  get "superusers", controller: 'superusers', action: 'index', as: :superusers
  post "superusers/add", controller: 'superusers', action: 'add', as: :add_superusers
  delete "superusers/remove", controller: 'superusers', action: 'remove', as: :remove_superusers

  resources :payforms, shallow: true do
    collection do
      get :index
      post :index
      delete :prune
      get :go
      post :search
      get :search
      post :search
    end
    member do
      get :submit
      get :unsubmit
      get :approve
      get :skip
      get :unskip
      get :unapprove
      get :print
    end
    resources :payform_items do
      member do
        get :delete
      end
    end
  end


  resources :time_slots do
    member { get :rerender } #TODO: What should this be nested under, if anything?
  end

  resources :shifts, shallow: true do
    member do
      get :rerender
    end
    collection do
      get :unscheduled, as: :new_unscheduled
      get :show_active
      get :show_unscheduled
    end
    resource :report do
      resources :report_items
    end
    #NOTE: "sub_requests" is a clearer model name, we use subs for routing
    resources :sub_requests do
      member do
        put :take
        get :get_take_info
      end
    end
  end

  resources :reports, except: [:new] do
    member do
      get :popup
      get :update_reports
      post :custom_search
    end
    resources :report_items
  end

  resources :public_view do
    member do
      get  :for_location
      post :for_location
    end
  end

  resources :users do
    collection do
      post :update_superusers
    end
    member do
      post :toggle
      #get :toggle
      get :show_shifts
    end
    resources :punch_clocks
  end

  resources :locations, except: [:find_allowed_locations] do
    collection do
      get  :display_report_items
      post :display_report_items
      get  :toggle
      post :toggle
    end
  end
  #resources :locations, collection: {display_report_items: [:post, :get], toggle: [:post, :get], index: [:post, :get]}, except: [:index, :show, :edit, :find_allowed_locations, :new, :update, :create, :destroy]

  resources :data_types do
    resources :data_fields
    resources :data_objects, only: [:new, :create, :index]
  end

  resources :data_objects do
    resources :data_entries do
      member do
        put :edit
        put :update
      end
    end
  end

  resources :departments, shallow: true do
    resources :users do
      collection do
        get :import
        get :mass_add
        post :mass_create
        get :autocomplete
        post :restore
        post :search
        post :save_import
        post :verify_import
      end
    end
    resources :loc_groups do
      get :toggle, on: :member
    end
    resources :locations
    resources :roles do
      member do
        get  :users
        post :users
      end
    end
    resources :categories
    put '/:id/disable', controller: "categories", action: "disable"
    put '/:id/enable', controller: "categories", action: "enable"
  end

  resources :user_profile_fields
  resources :user_profiles do
    collection do
      post :search
    end
  end

  match "/facebook", controller: "user_profiles", action: "facebook", as: :facebook, via: [:get, :post]
  match "/email_group", controller: "shifts", action: "email_group", as: :email_group, via: [:get, :post]

  resources :punch_clock_sets

  # permissions are always created indirectly so there we only need an index method to list them
  resources :permissions, only: :index

  resources :stats do
    collection do
      post :for_user
      get :for_user
      post :for_location
      get :for_location
      get  :index
      post :index
    end
  end

  #map.report_items 'report_items/for_location', controller: 'report_items', action: 'for_location'

  get '/dashboard', controller: 'dashboard', action: 'index', as: :dashboard
  get '/access_denied', controller: 'application', action: 'access_denied', as: :access_denied

	resources :templates  do
    collection do
      post :update_locations
    end
		resources :requested_shifts
		resources :shift_preferences
		resources :template_time_slots
  end

  root to: "dashboard#index"

  get '/status' => 'status#index'

  match '/test_new_lists', controller: 'reports', action: 'tasks_and_objects_list', as: :test_new_lists, via: [:get, :post]
  match '/update_data_objects', controller: 'data_objects', action: 'update_data_objects', as: :update_data_objects, via: [:get, :post]
  match '/active_tasks', controller: 'tasks', action: 'active_tasks', as: :active_tasks, via: [:get, :post]

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  belongs_to :remover, class_name: "User"
  belongs_to :department

  has_and_belongs_to_many :locations
  has_and_belongs_to_many :loc_groups

  validate :content_or_label, :presence_of_locations, :proper_time

  attr_accessor :start_date
  attr_accessor :start_time
  attr_accessor :end_date
  attr_accessor :end_time

  #before_destroy :destroy_user_sinks_user_sources    TODO:  this validation fails, but also is never called as we never delete notices.
  scope :in_department, ->(dept){ where(department_id: dept)}
  scope :created_by, ->(user){ where(author_id: user)}
  scope :inactive, -> {where(" end < ?", Time.now.utc)}
  scope :not_link, -> {where("type != ?", "Link")}
  scope :upcoming,  -> {where("start > ? ", Time.now.utc)}
  scope :global,  -> {where(department_wide: true)}
  scope :active, -> {where("start <= ? AND end is ? OR end > ?", Time.now.utc, nil, Time.now.utc)}

  def self.active_links
    Link.active
  end

  def self.active_notices
    Announcement.active.ordered_by_start + Sticky.active.ordered_by_start
  end

  def display_for
    display_for = []
    #TODO Figure out why users isn't a valid method
    #display_for.push "for users #{self.users.collect{|n| n.name}.to_sentence}" unless self.users.empty?
    #display_for.push "for locations #{self.locations.collect{|l| l.short_name}.to_sentence}" unless self.locations.empty?
    display_for.join "<br/>"
  end

  def is_upcoming?
    return self.start > Time.now if self.start
    false
  end

  def display_locations
    if self.department_wide
      return self.department.locations
    end
    a = self.locations
    b = self.loc_groups.collect(&:locations).flatten
    (a + b).uniq
  end

  def remove(user)
    self.errors.add(:base, "This notice has already been removed by #{remover.name}.") and return if self.remover && self.end
    self.start = Time.now if self.start > Time.now
    self.end = Time.now
    self.indefinite = false
    self.remover = user
    true if self.save
  end

  def content_with_formatting
    content.sanitize_and_format
  end

  private
  #Validations
  def presence_of_locations
    if self.display_locations.empty?
			errors.add  :base, "Your #{self.class.name.downcase} must display somewhere"
  	end
	end

  def proper_time
    errors.add :base, "Start/end time combination is invalid." if self.end && self.start >= self.end
  end

	def content_or_label
		if self.content.blank?
			if self.type == "Link"
				errors.add :base, "Your link must have a label"
			else
				errors.add :base, "Your #{self.type.downcase} must have content"
			end
		end
	end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  layout 'shifts'

  def archive
    require_department_admin
    @notices = Notice.inactive
  end

  def destroy
    @notice = Notice.find(params[:id])
    unless @notice.class.name == "Sticky" || current_user.is_admin_of?(current_department) || current_user == @notice.author
      flash[:error] = "You are not authorized to remove this #{@notice.type.downcase}"
      redirect_to :back and return
    end
    unless @notice.active? || @notice.start > Time.now
      flash[:error] = "This #{@notice.type.downcase} was already removed on #{@notice.end}"
      redirect_to :back and return
    end
    if @notice.remove(current_user) && @notice.save
      flash[:notice] = "#{@notice.type} successfully removed"
      redirect_to :back
    else
      flash[:error] = "Error removing #{@notice.type.downcase}"
      redirect_to :back
    end
  end

  def update_message_center
    respond_to do |format|
      format.js
    end
  end

  protected

  def set_sources(notice)
    if params[:department_wide_locations] && current_user.is_admin_of?(current_department)
      notice.department_wide = true
      notice.save!
    end
		if params[:for_location_groups]
      params[:for_location_groups].each do |loc_group_id|
				@loc_group = LocGroup.find(loc_group_id)
				if current_user.is_admin_of?(@loc_group) || notice.class.name == "Sticky"
          notice.loc_groups << @loc_group
      	end
			end
    end
    if params[:for_locations]
      params[:for_locations].each do |location_id|
        notice.locations << Location.find(location_id)
      end
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
  def loc_group_checked_notice?(loc_group, notice)
    notice.loc_groups.each do |lg|
      return true if lg == loc_group
    end
    loc_group.locations.active.each do |loc|
      return false if !location_checked_notice?(loc, notice)
    end
    true
  end

  def location_checked_notice?(location, notice)
		return @current_shift_location == location if @current_shift_location
    notice.display_locations.each do |loc|
      return true if loc == location
    end
		false
  end

  # if the radio_button should be selected
  # returns the result for the indefinite radio_button if indifinite is true
  # returns the result for the End radio_button if indefinite is false
  def end_time_check(indefinite)
    if indefinite
      return @announcement.created_at && @announcement.indefinite
    else
      return @announcement.created_at && !@announcement.indefinite
    end
  end

  def start_time_check(now)
    if now
      !@announcement.is_upcoming?
    else
      @announcement.is_upcoming?
    end
  end
end

app/views/notices/_all_notices.html.erb
<% if current_user.is_admin_of?(current_department) %>
  <% unless Notice.upcoming.empty? %>

  <div id = "upcoming">
    <fieldset class = "index">
      <legend>Upcoming</legend>
	  <div class="index">
      <%= render partial: 'notices/notice', collection: Notice.upcoming %>
      </div>
    </fieldset>
  </div>
  <br />
  <% end %>
<% end %>
<div id = "for_department">
    <%= render partial: 'notices/for_category', locals: {givencollection: current_department.current_notices, legend: "Department Wide"} %>
</div>

<% if current_user.user_config.view_loc_groups.empty? %>
  <p>You have not selected any location groups to view! Fix that in your
    <%= link_to "User settings", edit_user_config_path(current_user.user_config) %>.</p>
<% end %>
<div id = "location_notices">
  <% current_user.user_config.view_loc_groups.each do |loc_group| %>
		<% loc_group.locations.each do |loc| %>
		    <% @loc_current_notices = loc.current_notices %>
		    <% unless @loc_current_notices.empty? %>
		      <fieldset class ="index">
		        <legend><%= loc.name %></legend>
		          <div>	        
		            <%= render partial: 'notices/notice', collection: @loc_current_notices, locals: {html_class: "index_notice"}%> 
		          </div>
		      </fieldset>
		      <br/>
		    <% end %>
		  <% end %>
  <% end %>
</div>

app/views/notices/_announcement.html.erb
<div class="alert alert-info notice announcement" title="<%= "Posted on #{announcement.start.to_date} at #{announcement.start.to_s(:am_pm)}" %>">
  <% if current_user.is_admin_of?(current_department) || announcement.author == current_user%>
    <% if announcement.active? %>
      <%= link_to '&times;'.html_safe, notice_path(announcement),
      confirm: 'Are you sure you want to remove this announcement?',
      method: :delete, class: 'close', title: 'Delete Announcement', data: {
      toggle: 'tooltip', placement: 'bottom' } %>
    <% end %>
    <%= link_to edit_announcement_path(announcement),
    title: 'Edit Announcement', id: 'edit', data: {
     toggle: "modal", target: "#modal", placement: 'bottom',
     remote: edit_announcement_path(announcement, layout: "false")} do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
  <% end %>

  <div class="<%= html_class %>">
    <%= announcement.content_with_formatting %>
  </div>
  <div class="notice-author">
    By <%= link_to announcement.author.name, user_profile_path(announcement.author.login) %>
  </div>
</div>

app/views/notices/_dashboard.html.erb
<%unless @current_notices.empty? %>
  <%= render partial: 'notices/notice', collection: @current_notices, locals: {html_class: "dashboard_notice"} %>
<% else %>
  <em>There are no department-wide announcements at this time.</em>
<% end %>

app/views/notices/_error_messages.html.erb
  <%= error_messages_for 'sticky', 'announcement', 'link' %>

app/views/notices/_for_category.html.erb
<% unless givencollection.empty? %>
  <fieldset class = "index">
    <legend><%= legend %></legend>
      <%= render partial: 'notices/notice', collection: givencollection, locals: {html_class: "index_notice"} %>
  </fieldset>
  <br />
<% end %>

app/views/notices/_link.html.erb
<li class="link_with_url">
	<% if link.active? && (current_user.is_admin_of?(link.department) || current_user == link.author) %>
		<%= link_to '[x]', { controller: 'links', action: 'destroy', id: link.id },
							       confirm: "Are you sure you want to remove this link?",
					       method: :delete %>
	<% end %>
	<%= link_to link.content, link.url, target: "_blank" %>
	<div class="link_url">
    	<%= link.url %>
	</div>
</li>

app/views/notices/_locations.html.erb
<fieldset class = "index"><legend>Where:</legend>
<% if current_user.is_admin_of?(current_department) && notice.class.name != "Sticky" %>
  	<%= check_box_tag :department_wide_locations, current_department.id, false %>
  	<%= label_tag "department_wide_locations", text = current_department.name + " (all locations)"%>
<% end %>

<div id = "all_locations">
 	 <% for loc_group in current_department.loc_groups do %>
      <% next if !loc_group.active %>
      <% if current_user.is_admin_of?(loc_group) || notice.class.name == "Sticky" %>
	<li id = "notice_li">
	   <%= check_box_tag "for_location_groups[]", loc_group.id, loc_group_checked_notice?(loc_group, notice)%>
	   <%= label_tag "location_group_#{loc_group.id}", text = loc_group.name %>:
	   <% for location in loc_group.locations do %>
        <% next if !location.active %>
	      <%= check_box_tag "for_locations[]", location.id, location_checked_notice?(location, notice) %>
	      <%= label_tag "location_#{location.id}", text = location.short_name %>
	      <% unless location == loc_group.locations.last %>, <%end%>
	   <% end %>
	</li>
  <% end %>
<% end %>
	</div>
</fieldset>

app/views/notices/_notice.html.erb
<% if notice.class.name == 'Sticky' %>
  <%= render partial: 'notices/sticky', object: notice, locals: { html_class: html_class } %>
<% elsif notice.class.name == 'Announcement' %>
  <%= render partial: 'notices/announcement', object: notice, locals: { html_class: html_class } %>
<% end %>

app/views/notices/_sticky.html.erb
<div class="alert alert-warning notice sticky" title="<%= "Posted on #{sticky.start.to_date} at #{sticky.start.to_s(:am_pm)}" %>">
  <div class="right">
    <% if sticky.active? %>
      <%= link_to '&times;'.html_safe, notice_path(sticky),
      confirm: "Are you sure you want to remove this sticky? It will be removed for all users and all locations.",
      method: :delete, class: 'close', title: 'Delete Sticky', data: {
      toggle: 'tooltip', placement: 'bottom' } %>
    <% end %>
  </div>

  <div class="<%= html_class %>">
  	<%= sticky.content_with_formatting %>
  </div>

  <div class="notice-author">
    By <%= link_to sticky.author.name, user_profile_path(sticky.author.login) %>
    <%= "#{distance_of_time_in_words(sticky.start, Time.now, true)} ago" %>
  </div>
  <div class="grayright">
    <%= sticky.display_for %>
  </div>
</div>

app/views/notices/archive.html.erb
<h1 id = "page_title" > Notices archive </h1>
<fieldset class="index">
  <legend>Inactive announcements</legend>
  <%= render partial: 'notices/notice', collection: @notices.select{|n| n.type=='Announcement'}, locals: {html_class: "index_notice"} %>
</fieldset>
<fieldset class="index">
  <legend>Inactive stickies</legend>
  <%= render partial: 'notices/notice', collection: @notices.select{|n| n.type=='Sticky'}, locals: {html_class: "index_notice"} %>
</fieldset>
<fieldset class="index">
  <legend>Inactive links</legend>
  <%= render partial: 'notices/link', collection: @notices.select{|n| n.type=='Link'} %>
</fieldset>

app/views/notices/index.html.erb
<% content_for :title, "Notices" %>
<h1 id="page_title">Notices</h1>
<%= link_to_post_a_sticky() %>
<%= link_to_post_an_announcement %> <br /> <br />
<div id="all_notices">
  <%= render partial: "all_notices" %>
</div>

app/views/notices/update_message_center.js.erb
// unless current_user.current_shift.nil?
//   page.replace_html "message_center", partial: 'notices/notice', collection: current_user.current_shift.report.get_notices, locals: {html_class: "report_notice"}
//   page << "tb_init('a#edit');"
// end

<% unless current_user.current_shift.nil? %>
	$('#message_center').html('<%= escape_javascript render partial: 'notices/notice', collection: current_user.current_shift.report.get_notices, locals: {html_class: "report_notice"}  %>');
	tb_init('a#edit');
<% end %>