config/routes.rb
Shifts::Application.routes.draw do

  resources :tasks do
    post :make_entry, on: :member
    get 'update_tasks', on: :collection
    get :completed_tasks, on: :member
    get :missed_tasks, on: :member
  end

  resources :shifts_tasks
  resources :calendar_feeds, only: :index
  resources :template_time_slots
  resources :stickies
  resources :announcements
  resources :links
  resources :repeating_events
  resources :restrictions
  resources :punch_clocks
  resources :punch_clock_sets
  resources :user_sessions
  resources :password_resets
  resources :user_configs, only: [:edit, :update]
  resources :sub_requests
  resources :notices do
    get 'archive', on: :collection
    get 'update_message_center', on: :collection
  end
  resources :payform_item_sets
  resources :payform_sets
  resources :department_configs, only: [:edit, :update]
  resources :requested_shifts
  resources :templates
  resources :payform_items
  resources :requested_shifts
  resources :templates



  resources :stats do
    collection do
      get  :for_user
      post :for_user
      get  :for_location
      post :for_location
      get  :index
      post :index
    end
  end


  resource :app_config, only: [:edit, :update]
  #   get :edit, on: :collection
  # end
  # get "app_config" => 'app_configs#edit', as: :edit_app_config

  resources :calendars do
    member do
      get  :prepare_copy
      get  :apply_schedule
      post :apply_schedule
      post :toggle
      post :copy
    end
    collection do
     get :prepare_wipe_range
     post :wipe_range
    end
  end


  scope '/firstrun' do
    with_options controller: 'first_run' do |f|
      f.match '/first_app_config', action: 'new_app_config', as: :first_app_config, via: :get
      f.match '/first_department', action: 'new_department', as: :first_department, via: :get
      f.match '/first_user', action: 'new_user', as: :first_user, via: :get
      f.match '/create_first_app_config', action: 'create_app_config', as: :create_first_app_config, via: :post
      f.match '/create_first_department', action: 'create_department', as: :create_first_department, via: :post
      f.match '/create_first_user', action: 'create_user', as: :create_first_user, via: :post
    end
  end

  # match 'login' => 'user_sessions#new', as: :login
  # match 'logout' => 'user_sessions#destroy', as: :logout
  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  match "email_reminders", controller: 'payforms', action: 'email_reminders', as: :email_reminders, via: [:get, :post]
  match "reminders_advanced_options", controller: 'payforms', action: 'reminders_advanced_options', as: :reminders_advanced_options, via: [:get, :post]
  match  "warnings_advanced_options", controller: 'payforms', action: 'warnings_advanced_options', as: :warnings_advanced_options, via: [:get, :post]

  #TODO: get rid of sessions controller and move logout action to user_session controller and name it cas_logout
  match "cas_logout", controller: 'sessions', action: 'logout', as: :cas_logout, via: [:get, :post]
  match 'calendar_feeds/grab/:user_id/:token', controller: 'calendar_feeds', action: 'grab', as: :calendar_feed, via: [:get, :post]
  match 'calendar_feeds/reset', controller: 'calendar_feeds', action: 'reset', as: :calendar_feed_reset, via: [:get, :post]

  # routes for managing superusers

  get "superusers", controller: 'superusers', action: 'index', as: :superusers
  post "superusers/add", controller: 'superusers', action: 'add', as: :add_superusers
  delete "superusers/remove", controller: 'superusers', action: 'remove', as: :remove_superusers

  resources :payforms, shallow: true do
    collection do
      get :index
      post :index
      delete :prune
      get :go
      post :search
      get :search
      post :search
    end
    member do
      get :submit
      get :unsubmit
      get :approve
      get :skip
      get :unskip
      get :unapprove
      get :print
    end
    resources :payform_items do
      member do
        get :delete
      end
    end
  end


  resources :time_slots do
    member { get :rerender } #TODO: What should this be nested under, if anything?
  end

  resources :shifts, shallow: true do
    member do
      get :rerender
    end
    collection do
      get :unscheduled, as: :new_unscheduled
      get :show_active
      get :show_unscheduled
    end
    resource :report do
      resources :report_items
    end
    #NOTE: "sub_requests" is a clearer model name, we use subs for routing
    resources :sub_requests do
      member do
        put :take
        get :get_take_info
      end
    end
  end

  resources :reports, except: [:new] do
    member do
      get :popup
      get :update_reports
      post :custom_search
    end
    resources :report_items
  end

  resources :public_view do
    member do
      get  :for_location
      post :for_location
    end
  end

  resources :users do
    collection do
      post :update_superusers
    end
    member do
      post :toggle
      #get :toggle
      get :show_shifts
    end
    resources :punch_clocks
  end

  resources :locations, except: [:find_allowed_locations] do
    collection do
      get  :display_report_items
      post :display_report_items
      get  :toggle
      post :toggle
    end
  end
  #resources :locations, collection: {display_report_items: [:post, :get], toggle: [:post, :get], index: [:post, :get]}, except: [:index, :show, :edit, :find_allowed_locations, :new, :update, :create, :destroy]

  resources :data_types do
    resources :data_fields
    resources :data_objects, only: [:new, :create, :index]
  end

  resources :data_objects do
    resources :data_entries do
      member do
        put :edit
        put :update
      end
    end
  end

  resources :departments, shallow: true do
    resources :users do
      collection do
        get :import
        get :mass_add
        post :mass_create
        get :autocomplete
        post :restore
        post :search
        post :save_import
        post :verify_import
      end
    end
    resources :loc_groups do
      get :toggle, on: :member
    end
    resources :locations
    resources :roles do
      member do
        get  :users
        post :users
      end
    end
    resources :categories
    put '/:id/disable', controller: "categories", action: "disable"
    put '/:id/enable', controller: "categories", action: "enable"
  end

  resources :user_profile_fields
  resources :user_profiles do
    collection do
      post :search
    end
  end

  match "/facebook", controller: "user_profiles", action: "facebook", as: :facebook, via: [:get, :post]
  match "/email_group", controller: "shifts", action: "email_group", as: :email_group, via: [:get, :post]

  resources :punch_clock_sets

  # permissions are always created indirectly so there we only need an index method to list them
  resources :permissions, only: :index

  resources :stats do
    collection do
      post :for_user
      get :for_user
      post :for_location
      get :for_location
      get  :index
      post :index
    end
  end

  #map.report_items 'report_items/for_location', controller: 'report_items', action: 'for_location'

  get '/dashboard', controller: 'dashboard', action: 'index', as: :dashboard
  get '/access_denied', controller: 'application', action: 'access_denied', as: :access_denied

	resources :templates  do
    collection do
      post :update_locations
    end
		resources :requested_shifts
		resources :shift_preferences
		resources :template_time_slots
  end

  root to: "dashboard#index"

  get '/status' => 'status#index'

  match '/test_new_lists', controller: 'reports', action: 'tasks_and_objects_list', as: :test_new_lists, via: [:get, :post]
  match '/update_data_objects', controller: 'data_objects', action: 'update_data_objects', as: :update_data_objects, via: [:get, :post]
  match '/active_tasks', controller: 'tasks', action: 'active_tasks', as: :active_tasks, via: [:get, :post]

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/models/restriction.rb
class Restriction < ActiveRecord::Base
  belongs_to :department

  has_and_belongs_to_many :locations
  has_and_belongs_to_many :loc_groups
  has_and_belongs_to_many :users

  validates_presence_of :starts, :expires
  validates_presence_of :max_hours,  unless: :max_subs, message: "and Max subs can't both be blank"
  attr_accessor :start_date
  attr_accessor :start_time
  attr_accessor :end_date
  attr_accessor :end_time
  before_validation :join_date_and_time


  scope :current, -> {where("starts <= ? and expires >= ?", Time.now, Time.now)}
  # Need to make Restriction connect with locations (and users) in the same way
  # that Notices and Locations/LocGroups are connected
  # def users
  #   self.user_sources.collect{|s| s.users}.flatten.uniq
  # end

  # def locations
  #   self.location_sources.collect{|s| s.locations}.flatten.uniq
  # end

  def join_date_and_time
    self.starts ||= self.start_date.to_date.to_time + self.start_time.seconds_since_midnight
    self.expires ||= self.end_date.to_date.to_time + self.end_time.seconds_since_midnight
  end

end

app/controllers/restrictions_controller.rb
class RestrictionsController < ApplicationController
  layout 'shifts'

  before_filter :require_department_admin

  def index
    @restrictions = Restriction.all
  end

  def show
    @restriction = Restriction.find(params[:id])
  end

  def new
    @restriction = Restriction.new
    @restriction.starts ||= Time.now.to_date.to_time
    @restriction.expires ||= Time.now.to_date.to_time
  end

  def create
    parse_date_and_time_output(params[:restriction])
    join_date_and_time(params[:restriction])

    #rename start => starts, end=> expires
    params[:restriction][:starts] = params[:restriction][:start]
    params[:restriction].delete :start
    params[:restriction][:expires] = params[:restriction][:end]
    params[:restriction].delete :end

    @restriction = Restriction.new(params[:restriction])
    begin
      Restriction.transaction do
        @restriction.save(validate: false) 
        set_sources #setting polymorphic user and location sources
        @restriction.save! #saving again to run validations
      end
    rescue Exception
      render action: "new"
    else
      flash[:notice] = "Successfully created restriction."
      redirect_to restrictions_path
    end
  end

  def edit
    @restriction = Restriction.find(params[:id])
  end

  def update
    @restriction = Restriction.find(params[:id])
    parse_date_and_time_output(params[:restriction])
    join_date_and_time(params[:restriction])
    if @restriction.update_attributes(params[:restriction])
      flash[:notice] = "Successfully updated restriction."
      redirect_to @restriction
    else
      render action: 'edit'
    end
  end

  def destroy
    @restriction = Restriction.find(params[:id])
    @restriction.destroy
    flash[:notice] = "Successfully destroyed restriction."
    redirect_to restrictions_url
  end

  protected
  # Can't do this until we decide what to do with restrictions
  def set_sources
    if params[:for_users]
      @restriction.users = parse_users_autocomplete(params[:for_users])
    end
    if params[:department_wide_locations] && current_user.is_admin_of?(current_department)
      # Do we allow department wide actions? -Hugh
      # @restriction.location_sources << current_department
      @restriction.loc_groups = current_department.loc_groups
      @restriction.locations = current_department.locations
    elsif params[:for_location_groups]
      params[:for_location_groups].each do |loc_group|
        lg = LocGroup.find(loc_group)
        @restriction.loc_groups << lg
        @restriction.locations += lg.locations
      end
    elsif params[:for_locations]
      params[:for_locations].each do |loc|
        @restriction.locations << Location.find_by_id(loc)
      end
    end
  end
end

app/helpers/restrictions_helper.rb
module RestrictionsHelper
end

app/views/restrictions/_form.html.erb
<%= form_for @restriction do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :starts %><br />
    <%= f.date_select :start_date, default: @restriction.starts, id: :start_date  %><br />
    <%= f.time_select :start_time, {
                include_start_time: true,
                include_end_time: false,
                default: @restriction.starts,
                                          } %>

  </p>
  <p>
    <%= f.label :expires %><br />
    <%= f.date_select :end_date, default: @restriction.expires.to_date, id: :end_date  %><br /	>
    <%= f.time_select :end_time, {
                include_start_time: true,
                include_end_time: false,
                default: @restriction.expires,
                                          } %>  </p>
  <p>
    <%= f.label :max_subs %><br />
    <%= f.text_field :max_subs %>
  </p>
  <p>
    <%= f.label :max_hours %><br />
    <%= f.text_field :max_hours %>
  </p>

  <span id ="advanced_link" style="display:none" >
  <%= link_toggle "advanced", "Show/hide advanced options", "fast" %>
  </span>
  <div id="advanced">
    <%= label_tag :for_users, "Search for a user, role, or department" %>
    <%= text_field_tag :for_users, nil, class: :autocomplete %>
    <%= javascript_tag do %>
      autocomplete_path = "<%= j autocomplete_department_users_path(current_department).html_safe %>"
      prepopulated_data = <%= users_to_autocomplete_json(@restriction.users) %>
      set_up_autocomplete("for_users", autocomplete_path, prepopulated_data)
    <% end %>
    <p>
      For locations: <br />
      <% if current_user.is_admin_of?(@department) %>
        <%= check_box_tag :department_wide_locations %><%= @department.name %> (all locations)<br />
      <% end %>
      <div id="all_locations">
      <% for loc_group in @department.loc_groups do %>
        &nbsp;&nbsp;&nbsp;
        <li id='restriction_li'>
          <%= check_box_tag "for_location_groups[]", loc_group.id, @restriction.loc_groups.include?(loc_group), disabled: false %><%= loc_group.name %>:
          <% for location in loc_group.locations do %>
            <%= check_box_tag "for_locations[]", location.id, @restriction.locations.include?(location), disabled: false %>
            <%= location.name %> &nbsp;
          <% end %>
          <br />
        </li>
      <% end %>
      </div>
    </p>
  </div>


  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/restrictions/edit.html.erb
<% title "Edit Restriction" %>

<%= render partial: 'form' %>

<p>
  <%= link_to "Show", @restriction %> |
  <%= link_to "View All", restrictions_path %>
</p>

app/views/restrictions/index.html.erb
<% title "Restrictions" %>

<table class = "tablesorter">
 <thead>
  <tr>
    <th>Starts</th>
    <th>Expires</th>
    <th>Max Subs</th>
    <th>Max Hours</th>
  </tr>
 </thead>
  <% for restriction in @restrictions %>
 <tbody>
	<tr>
      <td><%= restriction.starts %></td>
      <td><%= restriction.expires %></td>
      <td><%= restriction.max_subs %></td>
      <td><%= restriction.max_hours %></td>
      <td><%= link_to "Show", restriction %></td>
      <td><%= link_to "Edit", edit_restriction_path(restriction) %></td>
      <td><%= link_to "Destroy", restriction, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
 </tbody>
  <% end %>
</table>

<p><%= link_to "New Restriction", new_restriction_path %></p>

app/views/restrictions/new.html.erb
<% title "New Restriction" %>

<%= render partial: 'form' %>

<p><%= link_to "Back to List", restrictions_path %></p>

app/views/restrictions/show.html.erb
<% title "Restriction" %>

<p>
  <strong>Starts:</strong>
  <%= @restriction.starts %>
</p>
<p>
  <strong>Expires:</strong>
  <%= @restriction.expires %>
</p>
<p>
  <strong>Max Subs:</strong>
  <%= @restriction.max_subs %>
</p>
<p>
  <strong>Max Hours:</strong>
  <%= @restriction.max_hours %>
</p>

<p>
  <%= link_to "Edit", edit_restriction_path(@restriction) %> |
  <%= link_to "Destroy", @restriction, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to "View All", restrictions_path %>
</p>