config/routes.rb
Shifts::Application.routes.draw do

  resources :tasks do
    post :make_entry, on: :member
    get 'update_tasks', on: :collection
    get :completed_tasks, on: :member
    get :missed_tasks, on: :member
  end

  resources :shifts_tasks
  resources :calendar_feeds, only: :index
  resources :template_time_slots
  resources :stickies
  resources :announcements
  resources :links
  resources :repeating_events
  resources :restrictions
  resources :punch_clocks
  resources :punch_clock_sets
  resources :user_sessions
  resources :password_resets
  resources :user_configs, only: [:edit, :update]
  resources :sub_requests
  resources :notices do
    get 'archive', on: :collection
    get 'update_message_center', on: :collection
  end
  resources :payform_item_sets
  resources :payform_sets
  resources :department_configs, only: [:edit, :update]
  resources :requested_shifts
  resources :templates
  resources :payform_items
  resources :requested_shifts
  resources :templates



  resources :stats do
    collection do
      get  :for_user
      post :for_user
      get  :for_location
      post :for_location
      get  :index
      post :index
    end
  end


  resource :app_config, only: [:edit, :update]
  #   get :edit, on: :collection
  # end
  # get "app_config" => 'app_configs#edit', as: :edit_app_config

  resources :calendars do
    member do
      get  :prepare_copy
      get  :apply_schedule
      post :apply_schedule
      post :toggle
      post :copy
    end
    collection do
     get :prepare_wipe_range
     post :wipe_range
    end
  end


  scope '/firstrun' do
    with_options controller: 'first_run' do |f|
      f.match '/first_app_config', action: 'new_app_config', as: :first_app_config, via: :get
      f.match '/first_department', action: 'new_department', as: :first_department, via: :get
      f.match '/first_user', action: 'new_user', as: :first_user, via: :get
      f.match '/create_first_app_config', action: 'create_app_config', as: :create_first_app_config, via: :post
      f.match '/create_first_department', action: 'create_department', as: :create_first_department, via: :post
      f.match '/create_first_user', action: 'create_user', as: :create_first_user, via: :post
    end
  end

  # match 'login' => 'user_sessions#new', as: :login
  # match 'logout' => 'user_sessions#destroy', as: :logout
  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  match "email_reminders", controller: 'payforms', action: 'email_reminders', as: :email_reminders, via: [:get, :post]
  match "reminders_advanced_options", controller: 'payforms', action: 'reminders_advanced_options', as: :reminders_advanced_options, via: [:get, :post]
  match  "warnings_advanced_options", controller: 'payforms', action: 'warnings_advanced_options', as: :warnings_advanced_options, via: [:get, :post]

  #TODO: get rid of sessions controller and move logout action to user_session controller and name it cas_logout
  match "cas_logout", controller: 'sessions', action: 'logout', as: :cas_logout, via: [:get, :post]
  match 'calendar_feeds/grab/:user_id/:token', controller: 'calendar_feeds', action: 'grab', as: :calendar_feed, via: [:get, :post]
  match 'calendar_feeds/reset', controller: 'calendar_feeds', action: 'reset', as: :calendar_feed_reset, via: [:get, :post]

  # routes for managing superusers

  get "superusers", controller: 'superusers', action: 'index', as: :superusers
  post "superusers/add", controller: 'superusers', action: 'add', as: :add_superusers
  delete "superusers/remove", controller: 'superusers', action: 'remove', as: :remove_superusers

  resources :payforms, shallow: true do
    collection do
      get :index
      post :index
      delete :prune
      get :go
      post :search
      get :search
      post :search
    end
    member do
      get :submit
      get :unsubmit
      get :approve
      get :skip
      get :unskip
      get :unapprove
      get :print
    end
    resources :payform_items do
      member do
        get :delete
      end
    end
  end


  resources :time_slots do
    member { get :rerender } #TODO: What should this be nested under, if anything?
  end

  resources :shifts, shallow: true do
    member do
      get :rerender
    end
    collection do
      get :unscheduled, as: :new_unscheduled
      get :show_active
      get :show_unscheduled
    end
    resource :report do
      resources :report_items
    end
    #NOTE: "sub_requests" is a clearer model name, we use subs for routing
    resources :sub_requests do
      member do
        put :take
        get :get_take_info
      end
    end
  end

  resources :reports, except: [:new] do
    member do
      get :popup
      get :update_reports
      post :custom_search
    end
    resources :report_items
  end

  resources :public_view do
    member do
      get  :for_location
      post :for_location
    end
  end

  resources :users do
    collection do
      post :update_superusers
    end
    member do
      post :toggle
      #get :toggle
      get :show_shifts
    end
    resources :punch_clocks
  end

  resources :locations, except: [:find_allowed_locations] do
    collection do
      get  :display_report_items
      post :display_report_items
      get  :toggle
      post :toggle
    end
  end
  #resources :locations, collection: {display_report_items: [:post, :get], toggle: [:post, :get], index: [:post, :get]}, except: [:index, :show, :edit, :find_allowed_locations, :new, :update, :create, :destroy]

  resources :data_types do
    resources :data_fields
    resources :data_objects, only: [:new, :create, :index]
  end

  resources :data_objects do
    resources :data_entries do
      member do
        put :edit
        put :update
      end
    end
  end

  resources :departments, shallow: true do
    resources :users do
      collection do
        get :import
        get :mass_add
        post :mass_create
        get :autocomplete
        post :restore
        post :search
        post :save_import
        post :verify_import
      end
    end
    resources :loc_groups do
      get :toggle, on: :member
    end
    resources :locations
    resources :roles do
      member do
        get  :users
        post :users
      end
    end
    resources :categories
    put '/:id/disable', controller: "categories", action: "disable"
    put '/:id/enable', controller: "categories", action: "enable"
  end

  resources :user_profile_fields
  resources :user_profiles do
    collection do
      post :search
    end
  end

  match "/facebook", controller: "user_profiles", action: "facebook", as: :facebook, via: [:get, :post]
  match "/email_group", controller: "shifts", action: "email_group", as: :email_group, via: [:get, :post]

  resources :punch_clock_sets

  # permissions are always created indirectly so there we only need an index method to list them
  resources :permissions, only: :index

  resources :stats do
    collection do
      post :for_user
      get :for_user
      post :for_location
      get :for_location
      get  :index
      post :index
    end
  end

  #map.report_items 'report_items/for_location', controller: 'report_items', action: 'for_location'

  get '/dashboard', controller: 'dashboard', action: 'index', as: :dashboard
  get '/access_denied', controller: 'application', action: 'access_denied', as: :access_denied

	resources :templates  do
    collection do
      post :update_locations
    end
		resources :requested_shifts
		resources :shift_preferences
		resources :template_time_slots
  end

  root to: "dashboard#index"

  get '/status' => 'status#index'

  match '/test_new_lists', controller: 'reports', action: 'tasks_and_objects_list', as: :test_new_lists, via: [:get, :post]
  match '/update_data_objects', controller: 'data_objects', action: 'update_data_objects', as: :update_data_objects, via: [:get, :post]
  match '/active_tasks', controller: 'tasks', action: 'active_tasks', as: :active_tasks, via: [:get, :post]

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/views/shifts/schedule/_day.html.erb
<% day_preprocessing(day) %>

<% @location_row = 1 %>
<% @location_group_row = 0 %>

<%#TODO: this whole section needs to be cleaned up... we should standardize ids, classes, etc... %>
<div id="<%= day.to_s %>" class="day_partial">
  <h4 class="trigger"><%= day.to_s(:just_date_long) %></h2>
  <div class="timeline" id="day_<%=day.to_s %>">
    <div class="days">
      <div class="day" style="height: <%= @table_pixels / (@table_height)%>px;"></div>
      <%= render partial: "shifts/schedule/left_loc_group", collection: @loc_groups, locals: {day: day} %>
    </div>
    <div class="timeline-data">
      <ul class="intervals" style="height: <%= @table_pixels / (@table_height)%>px;">
        <%= render partial: "shifts/schedule/hour_header", collection:  (@dept_start_hour...@dept_end_hour).to_a %>
      </ul>
      <%= render partial: "shifts/schedule/loc_group_row", collection: @loc_groups, locals: {day: day} %>
    </div>
  </div>

  <% unless @hidden_shifts.empty? %>
    <h3> Shifts outside of schedule:</h3>
    <ul class="hidden_shifts">
      <%= render partial: "shifts/schedule/hidden_shift", collection: @hidden_shifts %>
    </ul>
  <% end %>
</div>

app/views/shifts/schedule/_footer.html.erb
<div class="shifts_bottom" style="clear:both">
  <div class="shift_links">
    <%= link_to HTMLEntities.new.decode("&lt;&lt; Earlier"), {date: (@period_start - 7), anchor: @period_start - 1        }, class: "last_week"  %>
    <%= link_to HTMLEntities.new.decode("Later &gt;&gt;"),   {date: (@period_start + 7), anchor: @period_start + (2*7) - 1}, class: "next_week" %>
  </div>
</div>

app/views/shifts/schedule/_header.html.erb
<div class="shifts_top">
  <div class="shift_links">
    <%= link_to HTMLEntities.new.decode("&lt;&lt; Earlier"), {date: (@period_start - 7)}, class: "last_week" %>
    <%= link_to HTMLEntities.new.decode("Later &gt;&gt;"),   {date: (@period_start + 7)}, class: "next_week" %>
  </div>
  <div class="week_title">
    <%= @period_start.to_s(:just_date_short) %> to <%= (@period_start + 6.days).to_s(:just_date_short) %>
  </div>
</div>

app/views/shifts/schedule/_hidden_shift.html.erb
<li id="shift<%=hidden_shift.id%>" class="<%= hidden_shift.css_class(current_user) %> click_to_show">
  <%= hidden_shift.user.name %><br/>
  <%= hidden_shift.start.to_s(:am_pm) %> - <%= hidden_shift.end.to_s(:am_pm) %>
  (<%= hidden_shift.location.short_name %>)
</li>

app/views/shifts/schedule/_hour_header.html.erb
<li style="width: <%= 100/@hours_per_day.to_f %>%; left: <%= hour_header_counter*100/@hours_per_day.to_f %>%;" >
  <div class="hours">
    <div class="center_container">
      <div class="center_content">
        <%= Time.now.change(hour: hour_header).strftime("%l%p") %>
      </div>
    </div>
  </div>
  <%= render partial: "shifts/schedule/minutes", collection: (0..(@blocks_per_hour-1)).to_a %>
</li>

app/views/shifts/schedule/_left_loc_group.html.erb
<%= render partial: "shifts/schedule/left_location", collection: Location.active.in_group(left_loc_group), locals: {day: day} %>
<div class="day divider" style="height: <%= @divider_height %>px;"></div>

app/views/shifts/schedule/_left_location.html.erb
<div class="day" style="height: <%= @table_pixels / (@table_height) * (@location_rows[left_location].length) + @location_rows[left_location].length - 1 %>px;">
  <div class="center_container click_to_add_new" id="location<%=left_location.id%>_<%=day%>_label">
    <div class="center_content">
      <%= left_location.short_name %>
    </div>
  </div>
</div>
<% unless @location_rows_timeslots[left_location].nil? %>
  <div class="day" style="height: <%= @table_pixels / (@table_height) / 2 %>px;">
    <div class="center_container click_to_add_new_timeslot">
      <div class="center_content">
        signups
      </div>
    </div>
  </div>
<% end %>

app/views/shifts/schedule/_loc_group_row.html.erb
<% loc_group_preprocessing %>

<%= render partial: "shifts/schedule/location_row_set", collection: Location.active.in_group(loc_group_row).sort_by(&:short_name).reverse.sort_by(&:priority).reverse, locals: {day: day} %>
<ul class="events divider" style="height: <%= @divider_height %>px;"></ul>
<% @location_group_row += 1 %>

app/views/shifts/schedule/_location_row.html.erb
<ul id="location<%=location.id%>_<%=day%>_events" class="events" style="height:<%= @table_pixels / (@table_height)%>px;">
  <% if day < Date.today %>
    <li id="location<%=location.id%>_<%=day%>_free_time" style="width:100%;" class="no_signups"></li>
  <% else %>
    <%# location_preprocessing(location, day) %>
    <%= render partial: 'shifts/schedule/signup_bar', object: @signup_bar, locals: {location: location, day: day} %>
  <% end %>
  <%= render partial: "shifts/schedule/shift", collection: location_row %>
</ul>
<% @location_row += 1 %>

app/views/shifts/schedule/_minutes.html.erb
<div class="minutes" style="width: <%= 100.0/@blocks_per_hour%>%; left:<%= minutes_counter*(100.0/@blocks_per_hour) %>%;"></div>

app/views/shifts/schedule/_shift.html.erb
<li id="shift<%=shift.id%>" style="<%=shift_style(shift)%>" class="<%= shift.css_class(current_user) %> click_to_show">
  <div class="shift-time-overlay" style="position: absolute; left: -1px; top:-<%= @table_pixels / (@table_height) * @location_row + @location_row + @location_group_row + @location_group_row * @divider_height + @timeslot_rows / 2.0 * @table_pixels / (@table_height) %>px;">
    <%#= "#{shift.start.strftime("%l:%M%p")} - #{shift.end.strftime("%l:%M%p")}" %>
		</div>
  <div class="time-slot">
    <%= render partial: "shifts/schedule/sub", collection: shift.sub_requests %>

    <%= image_tag "overflow_arrow_right.png", {class: "right_arrow", alt: "right arrow", height: @table_pixels / @table_height + 1 } if @right_overflow %>
    <%= image_tag "overflow_arrow_left.png",  {class: "left_arrow",  alt: "left arrow",  height: @table_pixels / @table_height + 1 } if @left_overflow %>

    <div class="center_container">
      <div class="center_content">
        <%= shift.user.name %>
      </div>
    </div>
  </div>
</li>

app/views/shifts/schedule/_signup_bar.html.erb
<% show_text ||= false %>
<li id="location<%=location.id%>_<%=day%>_free_time" style="width:100%; z-index: -100" class="no_signups"></li>
<% current_block = 0 %>
<% while current_block < @total_blocks %>
  <% style = @signup_bar[current_block] %>
  <% start_block = current_block %>
  <% length = 1 %>
  <% while @signup_bar[current_block+1] == style %>
    <% length += 1 %>
    <% current_block += 1 %>
  <% end %>
    <li id="location<%=location.id%>_<%=day%>_slot" style="width:<%= length / @total_blocks * 100 %>%; left:<%= start_block / @total_blocks * 100 %>%" class="<%=style%> bar">
      <div class="time-slot">
        <div class="center_container">
          <div class="center_content signup_bar">
            <% if show_text and length >= 3 %>
              <%= style == "bar_open click_to_add_new" ? (link_to "sign up", new_shift_path) : "" %>
              <%= style == "bar_full no_signups" ? "full" : "" %>
              <%= style == "bar_pending no_signups" ? "pending" : "" %>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  
  <% current_block += 1 %>
<% end %>

app/views/shifts/schedule/_time_slot.html.erb
<li id="timeslot<%=time_slot.id%>" style="<%=shift_style(time_slot, Time.now)%>" class="click_to_add_new timeslot">
  <div class="time-slot">
    <div class="center_container">
      <div class="center_content">
        <%= link_to "sign up", new_shift_path %>
      </div>
    </div>
  </div>
</li>

app/views/shifts/schedule/_weekly.html.erb
<div class="filter-bar v2">
  <div class="calender-holder">
    <a href="#" class="icon-calender ico"></a>
    <div class="dates-range">
      <%= link_to shifts_path(date: (@period_start - 7)), class: "btn-prev" do %>
        <span class="icon-angle-left"></span>
      <% end %>
      <span class="date"><%= "#{@period_start.to_s(:just_date_short)} - #{(@period_start + 6.days).to_s(:just_date_short)}" %></span>
      <%= link_to shifts_path(date: (@period_start + 7)), class: "btn-next" do %>
        <span class="icon-angle-right"></span>
      <% end %>
      <a href="#" class="filter-btn"><span class="icon-filter"></span></a>
    </div>
  </div>
  <div class="slide">
    <div class="select time-filter">
      <select>
        <option>Weekly</option>
        <option>Weekly</option>
        <option>Weekly</option>
        <option>Weekly</option>
      </select>
    </div>
  </div>
  <div class="right-btns hidden-mobile">
    <%= link_to "Add New Shift", :new_shift, remote: true, class: "btn btn-primary" %>
  </div>
</div>

<div class="scheduletable">
  <table>
    <thead>
      <tr>
        <th class="select">
          <select>
            <option>Sort by Employees</option>
            <option>Option</option>
            <option>Option</option>
            <option>Option</option>
          </select>
        </th>
        <% @day_collection.each do |day| %>
        <th>
          <%= day.strftime('%^a') %>
          <span class="counter">
            <% if day == Date.today %>
              <em class="current">
                <%= day.strftime('%-d') %>
              </em>
            <% else %>
              <%= day.strftime('%-d') %>
            <% end %>
          </span>
        </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr class="hidden">
        <td colspan="8">Shifts</td>
      </tr>
      <% @employees.each do |employee| %>
      <% shifts = @shifts[employee.id] %>
      <tr>
        <td>
          <div class="image-holder">
            <%= link_to "#" do image_tag(employee.user_profile.photo.url(:thumbnail)) end %>
            <a href="#"><img src="images/img2.jpg" alt="image description"></a>
          </div>
          <div class="text">
            <strong class="title"><%= employee.name %></strong>
            <span class="userno">215-555-5555</span>
          </div>
        </td>
        <% @day_collection.each do |day| %>
        <td>
          <% shifts.each do |shift| %>
            <% if shift.start.between?(day.beginning_of_day, day.end_of_day) %>
            <%
              s = shift.start
              hour = s.strftime('%l')
              min = s.strftime(':%M') unless s.strftime('%M') != 0
              ampm = s.strftime('%p')
              start_time = "#{hour}#{min} #{ampm}"

              e = shift.end
              hour = e.strftime('%l')
              min = e.strftime(':%M') unless e.strftime('%M') != 0
              ampm = e.strftime('%p')
              end_time = "#{hour}#{min} #{ampm}"
            %>
            <%= link_to edit_shift_path(shift), remote: true do %>
            <div class="shift">
              <strong class="title"><%= employee.name %></strong>
              <span class="time">
                <%= start_time %> <em>-</em> <span><%= end_time %></span></span>
                <!-- TODO:  Add Position Title-->
              <span class="desciption">Position Name</span>
            </div>
            <% end %>
            <% end %>
          <% end %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>