config/routes.rb
Shifts::Application.routes.draw do

  resources :tasks do
    post :make_entry, on: :member
    get 'update_tasks', on: :collection
    get :completed_tasks, on: :member
    get :missed_tasks, on: :member
  end

  resources :shifts_tasks
  resources :calendar_feeds, only: :index
  resources :template_time_slots
  resources :stickies
  resources :announcements
  resources :links
  resources :repeating_events
  resources :restrictions
  resources :punch_clocks
  resources :punch_clock_sets
  resources :user_sessions
  resources :password_resets
  resources :user_configs, only: [:edit, :update]
  resources :sub_requests
  resources :notices do
    get 'archive', on: :collection
    get 'update_message_center', on: :collection
  end
  resources :payform_item_sets
  resources :payform_sets
  resources :department_configs, only: [:edit, :update]
  resources :requested_shifts
  resources :templates
  resources :payform_items
  resources :requested_shifts
  resources :templates



  resources :stats do
    collection do
      get  :for_user
      post :for_user
      get  :for_location
      post :for_location
      get  :index
      post :index
    end
  end


  resource :app_config, only: [:edit, :update]
  #   get :edit, on: :collection
  # end
  # get "app_config" => 'app_configs#edit', as: :edit_app_config

  resources :calendars do
    member do
      get  :prepare_copy
      get  :apply_schedule
      post :apply_schedule
      post :toggle
      post :copy
    end
    collection do
     get :prepare_wipe_range
     post :wipe_range
    end
  end


  scope '/firstrun' do
    with_options controller: 'first_run' do |f|
      f.match '/first_app_config', action: 'new_app_config', as: :first_app_config, via: :get
      f.match '/first_department', action: 'new_department', as: :first_department, via: :get
      f.match '/first_user', action: 'new_user', as: :first_user, via: :get
      f.match '/create_first_app_config', action: 'create_app_config', as: :create_first_app_config, via: :post
      f.match '/create_first_department', action: 'create_department', as: :create_first_department, via: :post
      f.match '/create_first_user', action: 'create_user', as: :create_first_user, via: :post
    end
  end

  # match 'login' => 'user_sessions#new', as: :login
  # match 'logout' => 'user_sessions#destroy', as: :logout
  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  match "email_reminders", controller: 'payforms', action: 'email_reminders', as: :email_reminders, via: [:get, :post]
  match "reminders_advanced_options", controller: 'payforms', action: 'reminders_advanced_options', as: :reminders_advanced_options, via: [:get, :post]
  match  "warnings_advanced_options", controller: 'payforms', action: 'warnings_advanced_options', as: :warnings_advanced_options, via: [:get, :post]

  #TODO: get rid of sessions controller and move logout action to user_session controller and name it cas_logout
  match "cas_logout", controller: 'sessions', action: 'logout', as: :cas_logout, via: [:get, :post]
  match 'calendar_feeds/grab/:user_id/:token', controller: 'calendar_feeds', action: 'grab', as: :calendar_feed, via: [:get, :post]
  match 'calendar_feeds/reset', controller: 'calendar_feeds', action: 'reset', as: :calendar_feed_reset, via: [:get, :post]

  # routes for managing superusers

  get "superusers", controller: 'superusers', action: 'index', as: :superusers
  post "superusers/add", controller: 'superusers', action: 'add', as: :add_superusers
  delete "superusers/remove", controller: 'superusers', action: 'remove', as: :remove_superusers

  resources :payforms, shallow: true do
    collection do
      get :index
      post :index
      delete :prune
      get :go
      post :search
      get :search
      post :search
    end
    member do
      get :submit
      get :unsubmit
      get :approve
      get :skip
      get :unskip
      get :unapprove
      get :print
    end
    resources :payform_items do
      member do
        get :delete
      end
    end
  end


  resources :time_slots do
    member { get :rerender } #TODO: What should this be nested under, if anything?
  end

  resources :shifts, shallow: true do
    member do
      get :rerender
    end
    collection do
      get :unscheduled, as: :new_unscheduled
      get :show_active
      get :show_unscheduled
    end
    resource :report do
      resources :report_items
    end
    #NOTE: "sub_requests" is a clearer model name, we use subs for routing
    resources :sub_requests do
      member do
        put :take
        get :get_take_info
      end
    end
  end

  resources :reports, except: [:new] do
    member do
      get :popup
      get :update_reports
      post :custom_search
    end
    resources :report_items
  end

  resources :public_view do
    member do
      get  :for_location
      post :for_location
    end
  end

  resources :users do
    collection do
      post :update_superusers
    end
    member do
      post :toggle
      #get :toggle
      get :show_shifts
    end
    resources :punch_clocks
  end

  resources :locations, except: [:find_allowed_locations] do
    collection do
      get  :display_report_items
      post :display_report_items
      get  :toggle
      post :toggle
    end
  end
  #resources :locations, collection: {display_report_items: [:post, :get], toggle: [:post, :get], index: [:post, :get]}, except: [:index, :show, :edit, :find_allowed_locations, :new, :update, :create, :destroy]

  resources :data_types do
    resources :data_fields
    resources :data_objects, only: [:new, :create, :index]
  end

  resources :data_objects do
    resources :data_entries do
      member do
        put :edit
        put :update
      end
    end
  end

  resources :departments, shallow: true do
    resources :users do
      collection do
        get :import
        get :mass_add
        post :mass_create
        get :autocomplete
        post :restore
        post :search
        post :save_import
        post :verify_import
      end
    end
    resources :loc_groups do
      get :toggle, on: :member
    end
    resources :locations
    resources :roles do
      member do
        get  :users
        post :users
      end
    end
    resources :categories
    put '/:id/disable', controller: "categories", action: "disable"
    put '/:id/enable', controller: "categories", action: "enable"
  end

  resources :user_profile_fields
  resources :user_profiles do
    collection do
      post :search
    end
  end

  match "/facebook", controller: "user_profiles", action: "facebook", as: :facebook, via: [:get, :post]
  match "/email_group", controller: "shifts", action: "email_group", as: :email_group, via: [:get, :post]

  resources :punch_clock_sets

  # permissions are always created indirectly so there we only need an index method to list them
  resources :permissions, only: :index

  resources :stats do
    collection do
      post :for_user
      get :for_user
      post :for_location
      get :for_location
      get  :index
      post :index
    end
  end

  #map.report_items 'report_items/for_location', controller: 'report_items', action: 'for_location'

  get '/dashboard', controller: 'dashboard', action: 'index', as: :dashboard
  get '/access_denied', controller: 'application', action: 'access_denied', as: :access_denied

	resources :templates  do
    collection do
      post :update_locations
    end
		resources :requested_shifts
		resources :shift_preferences
		resources :template_time_slots
  end

  root to: "dashboard#index"

  get '/status' => 'status#index'

  match '/test_new_lists', controller: 'reports', action: 'tasks_and_objects_list', as: :test_new_lists, via: [:get, :post]
  match '/update_data_objects', controller: 'data_objects', action: 'update_data_objects', as: :update_data_objects, via: [:get, :post]
  match '/active_tasks', controller: 'tasks', action: 'active_tasks', as: :active_tasks, via: [:get, :post]

  match "/delayed_job" => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :shift
  delegate :user, to: :shift
  has_many :report_items, dependent: :destroy

  validates_uniqueness_of :shift_id

  def get_notices
    a = self.shift.location.stickies.active + self.shift.location.announcements.active
    g = Notice.active.global.not_link
    # Custom search that sorts first by class then by start
    return (a + g).uniq.sort do |a, b|
      if a.class != b.class
        a.class.name <=> b.class.name
      else
        a.start <=> b.start
      end
    end
  end

  def get_links
     a = self.shift.location.links.active
     b = Link.global.active
     (a + b).sort_by(&:start).uniq
  end

  def data_objects
    self.shift.location.data_objects
  end

  def short_description
    "Shift in #{shift.location.name} (#{arrived.strftime("%I:%M%p")}-#{departed.strftime("%I:%M%p")})"
  end

  def duration
    (self.departed && self.arrived) ? ((self.departed - self.arrived) / 3600.0) : 0
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #AJAX requests will be returned without layout
  layout proc{ |c| c.params[:format] == "js" ? false : "application" }

  def show
    @report = params[:id] ? Report.find(params[:id]) : Report.where(shift_id: params[:shift_id]).first
    # @tasks = Task.in_location(@report.shift.location).active.after_now.delete_if{|t| t.kind == "Weekly" && t.day_in_week != @report.shift.start.strftime("%a")}
    tasks = Task.in_location(@report.shift.location).active.after_now
    # filters out daily and weekly tasks scheduled for a time later in the day
    tasks = tasks.delete_if{|t| t.kind != "Hourly" && Time.now.seconds_since_midnight < t.time_of_day.seconds_since_midnight}
    # filters out weekly tasks on the wrong day
    @tasks = tasks.delete_if{|t| t.kind == "Weekly" && t.day_in_week != @report.shift.start.strftime("%a") }
    return unless require_department_membership(@report.shift.department)
    @report_item = ReportItem.new
    @search_engine_name = current_department.department_config.search_engine_name
    @search_engine_url = current_department.department_config.search_engine_url
  end

  def tasks_and_objects_list
    @report = current_user.current_shift.report if current_user.current_shift
    loc_groups = LocGroup.all
    @loc_groups = loc_groups.select{ |lg| lg.users.include?(current_user) }
    tasks = []
    @loc_groups.each do |loc_group|
      tasks << loc_group.locations.map{ |loc| loc.tasks }.flatten.uniq.compact
    end
    tasks = tasks.flatten.uniq.compact
    tasks = Task.active.after_now & tasks
    # filters out daily and weekly tasks scheduled for a time later in the day
    tasks = tasks.delete_if{|t| t.kind != "Hourly" && Time.now.seconds_since_midnight < t.time_of_day.seconds_since_midnight}
    # filters out weekly tasks on the wrong day
    @tasks = tasks.delete_if{|t| t.kind == "Weekly" && t.day_in_week != @report.shift.start.strftime("%a") }
  end

  #Signing into a shift
  def create
    shift = Shift.find(params[:shift_id])
    if shift.start > 1.day.from_now
      flash[:error] = "You can't sign into a shift too far in advance"
      redirect_to dashboard_path and return
    end

    @report = Report.new(shift_id: params[:shift_id], arrived: Time.now)

    if current_user.current_shift || current_user.punch_clock
      flash[:error] = "You are already signed into a shift or punch clock."
    elsif @report.user!=current_user
      flash[:error] = "You can't sign into someone else's report."
    else
      @report.save
      @report.report_items << ReportItem.new(time: Time.now, content: "#{current_user.name} (#{current_user.login}) logged in from #{request.remote_ip}", ip_address: request.remote_ip)
      a = @report.shift
      a.signed_in = true
      a.save(validate: false) #ignore validations because this is an existing shift or an unscheduled shift
      redirect_to @report and return
    end
    redirect_to shifts_path
  end

  def edit
    @report = Report.find(params[:id])
    return unless user_is_owner_or_admin_of(@report.shift, @report.shift.department)
  end


  #periodically call remote function to update reports dynamically
  def update_reports
     @report = current_user.current_shift.report
     respond_to do |format|
       format.js
     end
  end

  # TODO: refactor into a model method on Report
  #Submitting a shift
  def update
    @report = Report.find(params[:id])
    return unless user_is_owner_or_admin_of(@report.shift, @report.shift.department) || current_user.is_admin_of?(@report.shift.location)

    if (params[:sign_out] and @report.departed.nil?) #don't allow duplicate signout messages
      @report.departed = Time.now
      @report.report_items << ReportItem.new(time: Time.now, content: "#{current_user.name} (#{current_user.login}) logged out from #{request.remote_ip}", ip_address: request.remote_ip)
      @report.shift.update_attribute(:end, Time.now) unless @report.shift.scheduled?
      # above method call isn't safe; it works because there are never sub requests on unscheduled shifts, but it'll cause validation problems
      # with shift.adjust_sub_requests if it ever does run. -ben
      @add_payform_item = true
    end

    if @report.update_attributes(params[:report]) && @report.shift.update_attribute(:signed_in, false)
      if @add_payform_item #don't allow duplicate payform items for a shift
        @payform_item = PayformItem.new(hours: @report.duration,
                                       category: (@report.shift.location.category || current_department.department_config.default_category),
                                       payform: Payform.build(@report.shift.location.loc_group.department, @report.user, Time.now),
                                       date: Date.today,
                                       description: @report.short_description,
                                       source_url: shift_report_path(@report.shift),
                                       source: current_user)
        UserMailer.delay.shift_report(@report.shift, @report, @report.shift.department)
        if @payform_item.save
          flash[:notice] = "Successfully submitted report and updated payform."
        else
          flash[:notice] = "Successfully submitted report, but payform did not update. Please manually add the job to your payform."
        end
      else
        flash[:error] = "That report has already been submitted."
      end
      respond_to do |format|
        format.html {redirect_to dashboard_path}
        format.js
      end
    else
      flash[:notice] = "Report not submitted.  You may not be the owner of this report."
      render action: 'show'
    end
  end


  def custom_search
    @key_word = params[:search]
    @search_engine_url = current_department.department_config.search_engine_url
    @search_url = @search_engine_url.concat(@key_word)
    respond_to do |format|
      format.js
      format.html{}
    end
  end



# Do we want this action? -ben
#  def destroy
#    @report = Report.find(params[:id])
 #   @report.destroy
  #  #ArMailer.deliver()
   # flash[:notice] = "Successfully destroyed report."
    #redirect_to reports_url
#  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def report_kbd_shortcut
    if request.env['HTTP_USER_AGENT'].downcase.match(/mac/i)
      'Cmd+Enter to quickly add to report!'
    else
      'Ctrl+Enter to quickly add to report!'
    end
  end
end

app/views/reports/_form.html.erb
<%= form_for([:shift, @report], url: shift_report_path) do |f| %>
  <%= f.error_messages %>
  <p><%= f.submit "Yes" %></p>
<% end %>

app/views/reports/_new_report_item_form.html.erb
<%= form_for [@report, @report_item], remote: true, id: 'report_item_form' do |f| %>
  <%= f.error_messages %>
  <%= f.text_area :content, placeholder: report_kbd_shortcut, id: 'item', size: '40x3', wrap: 'hard', class: 'form-control' %>
  <%= f.submit "Add to report", id: 'report_item_submit', title: report_kbd_shortcut, class: 'btn btn-primary', data: { disable_with: "Submitting..." } %>
  <div id="submit_button">
    <%= params[:popup] %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= html_id %>">
  <% @report ||= report %>
  <table id="report_view_table" class="table table-striped table-bordered">
    <tbody id="all_report_items">
      <%= render partial: 'reports/report_item', collection: @report.report_items %>
    </tbody>
  </table>
</div>

app/views/reports/_report_item.html.erb
<tr <%= raw 'id="current_report_item"' if @report.report_items.last == report_item %> class="list_report_item">
  <td class="timestamp">
    <span class="label label-default">
      <%= report_item.time.getlocal.to_s(:am_pm_secs) %>
    </span>
  </td>
  <td class="report_item_content">
    <%= report_item.content_with_formatting %>
  </td>
</tr>

app/views/reports/_report_popup.html.erb
<div id="report_popup_<%= report.id %>" class="popup popup_draghandle" style="display:none">
  <strong>Events:</strong>
  <ul>
  <% report.report_items.each do |item| %>
    <li><%= item.time.getlocal.to_s(:am_pm) %>: <%= item.content_with_formatting %></li>
  <% end %>
  </ul>
</div>
<%= javascript_tag "new Popup('report_popup_#{report.id}','report_link_#{report.id}')" %>

app/views/reports/_search.html.erb
<%= form_tag url_for(controller: 'reports', action: 'custom_search', id: @report.id), remote: true, class: 'form-horizontal' do %>
  <div class="input-group">
    <%= search_field_tag 'search', nil, class: 'form-control' %>
    <span class="input-group-btn">
      <%= submit_tag 'Search', class: 'btn btn-default', title: 'Search' %>
    </span>
  </div>

<% end %>

app/views/reports/custom_search.js.erb
// if @key_word.empty?
// else
// window.open('#{@search_url.to_s}', '_blank','menubar=1,resizable=1');
// end
<% unless @key_word.empty? %>
	window.open("<%= @search_url.to_s %>", '_blank',"menubar=1,resizable=1");
<% end %>

app/views/reports/new.html.erb
<% title "New Report" %>

<p>Are you sure you want to sign into a shift?</p>

<%= render partial: 'form' %>

<p><%= link_to "Back to List", shift_path(params[:shift_id]) %></p>

app/views/reports/show.html.erb
<% title "Shift Report: #{@report.shift.location.name}" %>

<div class="row">
  <% if current_user == @report.user && !@report.departed %>

    <div class="col-md-6">

      <div id="report_message_center" class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= "Message Center: #{@report.shift.location.short_name}" %>
          </h3>
        </div>
        <div class="panel-body">
          <div id="message_center">
            <%= render partial: 'notices/notice', collection: @report.get_notices, locals: { html_class: 'report_notice' } %>
          </div>
        </div>
        <div class="panel-footer">
          <%= link_to_post_a_sticky %>
          <%= link_to_post_an_announcement %>
        </div>
      </div>

      <% unless mobile_device? %>
        <%= content_tag :div, nil, id: 'update_notices', data: { frequency: 240 } %>
        <!-- The following is deprecated. Now in report_show.js in assets-->
        <%#= periodically_call_remote url: { controller: "notices", action: "update_message_center"}, frequency: 240 %>
      <% end %>
    </div>

    <div class="col-md-6">
      <div id="report_data_objects" class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Data Objects</h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'data_objects/report_data_object' %>
        </div>
      </div>

      <div id="useful_links" class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Useful Links</h3>
        </div>
        <div class="panel-body">
          <ul id="useful-links-list">
            <li><%= link_to 'All Active Tasks', active_tasks_path %></li>
            <li><%= link_to 'All Data Objects', update_data_objects_path %></li>
            <div id="report_links">
              <%= render partial: 'links/report_links', collection: current_user.current_shift.report.get_links, as: :link %>
            </div>
          </ul>
        </div>
        <div class="panel-footer">
          <%= link_to_post_a_link %>
        </div>
      </div>

      <% unless mobile_device? %>
        <%= content_tag :div, nil, id: "update_tasks", data: { frequency: 300 } %>
         <%# The following is deprecated. Now in report_show.js in assets %>
         <%#= periodically_call_remote url: { controller: "tasks", action: "update_tasks"}, frequency: 300 %>
      <% end %>

      <div id="shift_tasks" class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Shift Tasks</h3>
        </div>
        <div class="panel-body">
          <div id="tasks">
            <%= render partial: 'tasks/report_tasks' %>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= 'Search ' + "#{@search_engine_name}" %>
          </h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'reports/search' %>
        </div>
      </div>
    </div>
  <% end %>

</div>

<div class="row">
  <div class="col-md-12">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <% if @report.departed %>
            Submitted Report
          <% elsif current_user == @report.user %>
            Update Your Report
          <% else %>
            Live Report
          <% end %>
        </h3>
      </div>

      <div class="panel-body">
        <div class="row">
          <% if current_user == @report.user && !@report.departed %>
            <div class="col-md-6">
              <%= render partial: 'new_report_item_form' %>
            </div>
          <% end %>

          <div class="col-md-<%= current_user == @report.user && !@report.departed ? "6" : "12" %>">
            <% unless mobile_device? %>
              <%= content_tag :div, nil, id: 'update_report', data: { id: @report.id, frequency: 30 } %>
              <!-- The following is deprecated. Now in report_show.js in assets-->
              <%#= periodically_call_remote url: { controller: "reports", action: "update_reports", id: @report.id}, frequency: 30 %>
            <% end %>
            <h4>
              <%= link_to @report.shift.start.to_s(:just_date), shift_path(@report.shift) %> -
              <%= @report.shift.scheduled? ? "Scheduled for #{@report.shift.start.to_s(:am_pm)} - #{@report.shift.end.to_s(:am_pm)}" : 'Unscheduled' %> <br />
              <%= link_to @report.shift.user.name, user_profile_path(@report.shift.user.login) %> @
              <%= link_to @report.shift.location.name, controller: :locations, action: :display_report_items, id: @report.shift.location %>
            </h4>

            <% if current_user == @report.user && !@report.departed %>
              <%= render partial: 'report', locals: { html_id: 'dashboard_report_view' } %>
            <% else %>
              <%= render partial: 'report', locals: { html_id: 'report_view' } %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="panel-footer">
        <% if current_user == @report.user && !@report.departed %>
          <%= button_to "Submit your shift report", { action: :update, id: @report.id, sign_out: true }, method: :put, confirm: 'Are you sure you wish to sign out of this shift?', class: 'btn btn-success' %>
        <% end %>

        <% if @report.shift.signed_in? && (current_user != @report.shift.user && current_user.is_admin_of?(@report.shift.loc_group)) %>
          <%= button_to "Submit #{@report.shift.user.name}'s shift report", { controller: 'reports', action: :update, id: @report, sign_out: true }, method: :put, confirm: 'Are you sure you wish to sign the user out of this shift?', class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/reports/tasks_and_objects_list.html.erb
<!-- when you make an entry(make_entry.js.erb) it currently renders report tasks which is the 
same as below except the links for the tasks dont have the all_tasks param. The partial 
should instead have a conditional that adds the param to the link if you are on the all 
tasks page and leaves it off if you are on a normal shift report page. That would allow
the below code to be rendered in with a simple partial and would allow make_entry.js.erb
to load the proper tasks list after you complete a task. -->


<div id = "left_stuff">
  <fieldset id = "shift_tasks" class= "index">
	<legend>All Tasks</legend>
	<div id = "tasks">
    <%= render partial: 'tasks/report_tasks', locals: {all_tasks: true} %>
	</div>
  </fieldset>
</div>


<div id = "right_stuff">
  <fieldset id = "report_data_objects" class = "index">
     <legend>All Data Objects</legend>
     <% @loc_groups.each do |loc_group| %>
	     <div >
	     	<strong><%= loc_group.name %></strong>
	     </div>
	     <% unless loc_group.data_objects.empty? %>
		    <% loc_group.data_objects.each do |data_object| %>
			 	<div style="width: 60%; float:left">
			    	<%= link_to "Update #{data_object.name}", 
			    		new_data_object_data_entry_path(data_object), 
			    		title: "Record New Data Entry", 
			    		data: {toggle: "modal", target: "#modal", remote: new_data_object_data_entry_path(data_object, layout: "false")}%>
			    	<br/>
				</div>
			<% end %>
		<% else %>
		     <em>There are no data objects in this location.</em>
		<% end %>
		<div style="clear:both"></div>
	<% end %>
  </fieldset>
</div>

app/views/reports/update_reports.js.erb
<% unless current_user.current_shift.nil? %>
	$("#all_report_items").html('<%= escape_javascript render partial: "reports/report_item", collection: @report.report_items %>');
<% end %>